#ifndef COMMON_H
#define COMMON_H

enum logSeverity { LOG_DEBUG, LOG_INFO, LOG_WARNING, LOG_CRITICAL, LOG_FATAL };
enum workerMode  { MINSELL, TICKERAVG };

enum WorkState { ERROR = -1, INITIALISE, START, WAITINGFORTICKER, CREATESELL, WAITINGFORSELL, SELLORDER, SOLD, CREATEBUY, WAITINGFORBUY, BUYORDER, COMPLETE , REMOVING, REMOVED};

#endif // COMMON_H
